import React, { useEffect, useState } from 'react';
import SplitText from '../components/alpha/SplitText';
import ScrollReveal from '../components/alpha/ScrollReveal';
import Antigravity from '../components/alpha/Antigravity';
import { getPage } from '../controllers/apiController';
import SEO from '../components/layout/SEO';
import './TermsOfService.css';

const DEFAULT_PAGE = {
  hero_line1: 'Terms of Service',
  hero_line2: 'Our Agreement',
  sections: [
    {
      label: '01. Acceptance',
      title: 'Agreement to Terms',
      paragraphs: [
        'By accessing or using the sum up website and services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.',
        'We may update these terms from time to time. Your continued use of the platform following the posting of revised Terms of Service means that you accept and agree to the changes.'
      ],
    },
    {
      label: '02. User Accounts',
      title: 'Account Responsibilities',
      paragraphs: [
        'To access certain features of sum up, you may be required to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.',
        'You agree to notify us immediately of any unauthorized use of your account or any other breach of security. sum up will not be liable for any loss or damage arising from your failure to comply with this provision.'
      ]
    },
    {
      label: '03. Intellectual Property',
      title: 'Ownership & Content Rights',
      paragraphs: [
        'The Website and its original content, features, and functionality are owned by sum up and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.',
        'Content generated by you using sum up\'s AI tools ("Generated Content") is owned by you. You retain all rights, title, and interest in and to the Generated Content. However, you grant sum up a non-exclusive, worldwide, royalty-free license to use, host, and display the Generated Content for the purpose of operating and improving the services.'
      ],
    },
    {
      label: '04. Prohibited Uses',
      title: 'Acceptable Use Policy',
      paragraphs: [
        'You agree not to use the Services to generate, upload, or share content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.',
      ],
      bullets: [
        'Do not generate child sexual abuse material (CSAM) or explicit content.',
        'Do not generate content that promotes violence, hate speech, or discrimination.',
        'Do not use the platform to impersonate others or generate misleading deepfakes.',
        'Do not attempt to reverse engineer or bypass the safety filters of our models.'
      ]
    },
    {
      label: '05. Use License',
      title: 'Platform Usage',
      paragraphs: [
        'Permission is granted to temporarily download one copy of the materials on sum up\'s website for personal, non-commercial transitory viewing only.',
        'This is the grant of a license, not a transfer of title, and under this license you may not:'
      ],
      bullets: [
        'Modify or copy the platform\'s source code or proprietary assets.',
        'Use the materials for any commercial purpose, or for any public display (commercial or non-commercial).',
        'Attempt to decompile or reverse engineer any software contained on the website.',
        'Remove any copyright or other proprietary notations from the materials.',
      ],
    },
    {
      label: '06. Disclaimer',
      title: 'No Warranties',
      paragraphs: [
        'The materials on sum up\'s website are provided on an "as is" basis. sum up makes no warranties, expressed or implied, and disclaims all other warranties including implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement.',
        'We do not warrant that the results obtained from the use of the service will be entirely error-free, completely reliable, or meet your exact expectations.'
      ],
    },
    {
      label: '07. Limitation of Liability',
      title: 'Liability Caps',
      paragraphs: [
        'In no event shall sum up, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.'
      ]
    },
    {
      label: '08. Governing Law',
      title: 'Jurisdiction',
      paragraphs: [
        'These terms and conditions are governed by and construed in accordance with the applicable laws, and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.'
      ],
    },
  ],
};

const formatUpdatedAt = (value?: string | null) =>
  new Date(value || Date.now()).toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

const TermsOfService: React.FC = () => {
  const [pageData, setPageData] = useState(DEFAULT_PAGE);
  const [updatedAt, setUpdatedAt] = useState<string | null>(null);

  useEffect(() => {
    getPage('terms')
      .then((page: any) => {
        setPageData({
          ...DEFAULT_PAGE,
          ...page.content,
          sections: page.content?.sections || DEFAULT_PAGE.sections,
        });
        setUpdatedAt(page.updated_at || null);
      })
      .catch((err: any) => {
        console.error('Terms page load error:', err);
      });
  }, []);

  return (
    <div className="terms-container">
      <SEO 
        title="Terms of Service | sum up" 
        description={`${pageData.hero_line1} - ${pageData.hero_line2}`} 
        canonicalUrl={window.location.origin + '/terms'}
      />
      <section className="terms-hero-section">
        <div className="antigravity-wrapper" style={{ opacity: 0.8 }}>
          <Antigravity color="var(--color-text)" count={60} magnetRadius={12} fieldStrength={10} particleSize={1.2} autoAnimate={true} />
        </div>
        <div className="max-container">
          <h1 className="hero-title">
            <span className="hero-line-1">
              <SplitText text={pageData.hero_line1} delay={30} animationFrom={{ opacity: 0, transform: 'translate3d(0,40px,0)' }} animationTo={{ opacity: 1, transform: 'translate3d(0,0,0)' }} />
            </span>
            <span className="hero-line-2">
              <SplitText text={pageData.hero_line2} delay={30} animationFrom={{ opacity: 0, transform: 'translate3d(0,40px,0)' }} animationTo={{ opacity: 1, transform: 'translate3d(0,0,0)' }} />
            </span>
          </h1>
        </div>
      </section>

      <section className="terms-content-section">
        {pageData.sections.map((section, index) => {
          // Split "01. Acceptance" into "01." and " Acceptance"
          const labelParts = (section.label || '').split(' ');
          const labelNum = labelParts[0];
          const labelText = labelParts.slice(1).join(' ');

          return (
            <div key={`${section.title}-${index}`} className="terms-block">
              <ScrollReveal y={20} delay={0.1}>
                <span className="terms-label">
                  <span className="terms-label-num">{labelNum}</span>
                  <span className="terms-label-text">{labelText}</span>
                </span>
                <h2>{section.title}</h2>
                <div className="terms-text">
                  {(section.paragraphs || []).map((paragraph: string, paragraphIndex: number) => (
                    <p key={paragraphIndex}>{paragraph}</p>
                  ))}
                  {section.bullets?.length ? (
                    <ul>
                      {section.bullets.map((bullet: string, bulletIndex: number) => (
                        <li key={bulletIndex}>{bullet}</li>
                      ))}
                    </ul>
                  ) : null}
                </div>
              </ScrollReveal>
            </div>
          );
        })}

        <div className="last-updated">
          <p>Last updated: {formatUpdatedAt(updatedAt)}</p>
        </div>
      </section>
      <div className="pb-20 md:pb-40"></div>
    </div>
  );
};

export default TermsOfService;
